name: Jobbo
version: 1.1.2
main: land.face.jobbo.JobboPlugin
author: Faceguy
description: dey tuk our jerbs
depend:
  - Facecore
softdepend:
  - Waypointer
  - PlaceholderAPI
  - Strife
  - Citizens
api-version: 1.16

commands:
  jobbo:
    usage: /<command>
    aliases: [job]
    description: jibs